services:
  # FastAPI App
  app:
    build: .
    container_name: madrasa_app
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
      KEYDB_HOST: ${KEYDB_HOST}
      KEYDB_PORT: ${KEYDB_PORT}
      KEYDB_PASSWORD: ${KEYDB_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./static:/app/static
      - ./templates:/app/templates
    expose:
      - "8000"  # Only expose to internal network, not host
    networks:
      - app_network
      - observability_network
    depends_on:
      keydb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 30s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: madrasa_nginx
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS (for future SSL)
    volumes:
      - ./config/hosting/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro  # Mount static files for direct serving
      - ./uploads:/app/uploads:ro  # Mount uploads for direct serving
      - ./logs/nginx:/var/log/nginx  # Nginx logs
    networks:
      - app_network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 10s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: madrasa_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}" # Expose to host in development
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql:/docker-entrypoint-initdb.d:ro
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 10
      interval: 30s
      start_period: 30s
    command: >
      --default-authentication-plugin=caching_sha2_password
      --host-cache-size=0
      --pid-file=/tmp/mysqld.pid

  # KeyDB for caching and session storage
  keydb:
    image: eqalpha/keydb:latest
    container_name: madrasa_keydb
    restart: unless-stopped
    expose:
      - ${KEYDB_PORT}
    ports:
      - "${KEYDB_PORT}:${KEYDB_PORT}"
    volumes:
      - keydb_data:/data
      - ./config/keydb/keydb.conf:/etc/keydb/keydb.conf:ro
    command: ["keydb-server", "/etc/keydb/keydb.conf"]
    networks:
      - observability_network
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 10s
    environment:
      KEYDB_PASSWORD: ${KEYDB_PASSWORD}

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: madrasa_otel_collector
    restart: unless-stopped
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel/collector-config.yaml:/etc/otel-collector-config.yaml:ro
    expose:
      - "4317"
      - "4318"
      - "9464"
      - "13133"
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9464:9464"   # Prometheus metrics
      - "13133:13133" # Health check endpoint
    networks:
      - observability_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 15s
    depends_on:
      - jaeger

  # Jaeger for trace visualization
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: madrasa_jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector endpoint
      - "14250:14250"  # gRPC collector endpoint
    networks:
      - observability_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686"]
      timeout: 20s
      retries: 10
      start_period: 20s
      interval: 15s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: madrasa_prometheus
    restart: unless-stopped
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --storage.tsdb.retention.time=200h
      --web.enable-lifecycle
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - prometheus_data:/prometheus
      - ./config/otel/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      timeout: 20s
      retries: 10
      start_period: 20s
      interval: 15s
    depends_on:
      - otel-collector

volumes:
  prometheus_data:
    driver: local
  keydb_data:
    driver: local
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
  observability_network:
    driver: bridge
