# Hypercorn Configuration for Madrasha App
# ========================================

# Server Binding (also saved in server_config)
bind = ["0.0.0.0:80"]
backlog = 2048

# Worker Configuration
workers = 1
worker_class = "asyncio"
worker_connections = 1000

# Timeouts
timeout = 60
keep_alive = 5
graceful_timeout = 30

# Application Settings
preload_app = true
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(D)s'

# Logging
accesslog = "-"
errorlog = "-"
loglevel = "info"

# Security Settings
limit_concurrency = 1000
limit_max_requests = 1000
limit_max_requests_jitter = 50

# Performance Tuning
max_incomplete_event_size = 16777216
max_header_size = 16384
max_request_size = 16777216

# SSL/TLS (uncomment for production)
# certfile = "path/to/cert.pem"
# keyfile = "path/to/key.pem"

# Additional Headers
header = ["Server: MadrashaApp/1.0"]
