global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:9464']   # Fixed: use localhost and correct port
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'madrasa-app'
    static_configs:
      - targets: ['localhost:8000']   # Your app's metrics endpoint
    metrics_path: '/metrics'
    scrape_interval: 10s